name: Build EXE for Windows
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller selenium undetected-chromedriver pynput requests

      - name: Build EXE
        run: pyinstaller --onefile temv_gui.py  # 确保脚本名正确

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: app.exe
          path: dist/temv_gui.exe
